#: import THEME reflex.components.widgets.facelift_theme

<CustomPopup>:
    orientation: "vertical"
    padding: dp(20)
    spacing: dp(10)

    Label:
        id: lbl_message
        text: root.message
        halign: "center"
        valign: "middle"
        text_size: self.size
        font_name: THEME.FONT_BOLD
        color: THEME.TEXT
        font_size: "18sp"

    FormValueButton:
        id: btn_close
        text: root.button_text
        size_hint_y: None
        height: dp(48)
        on_release: root.on_button_press()
