<BooleanItem>:
  height: 60
  size_hint_y: None
  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_press: app.beep()
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.7
      text: root.name
      font_size: app.formats.font_size
    FormToggle:
      size_hint_x: None
      width: 250
      multiline: False
      font_size: app.formats.font_size
      text: 'ON' if root.value else 'OFF'
      state: 'down' if root.value else 'normal'
      on_release: root.value = True if self.state == 'down' else False
