<ColorItem>:
  value: "#ffffff"
  height: 60
  size_hint_y: None

  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_press: app.beep()
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.7
      text: root.name
      font_size: app.formats.font_size
    BoxLayout:
      size_hint_x: None
      width: 250

      orientation: "vertical"
      FormValueButton:
        canvas.after:
          Color:
            rgba: root.color
          RoundedRectangle:
            pos: self.x + dp(8), self.y + dp(9)
            size: self.width - dp(16), self.height - dp(18)
            radius: [dp(3)]
        on_press: app.beep()
        on_release:
          app.color_picker.callback = root.set_color
          app.color_picker.color = root.color
          app.manager.goto("color_picker")
