<DualNumberItem>:
  value: 0
  height: 60
  size_hint_y: None
  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_press: app.beep()
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.6
      text: root.name
      font_size: app.formats.font_size
    FormValueButton:
      size_hint_x: None
      width: 125
      text: "{: 0.4f}".format(root.value / root.ratio)
      font_size: app.formats.font_size
      on_press: app.beep()
      on_release: Factory.Keypad().show(root, 'scaled_value')
    FormValueButton:
      size_hint_x: None
      width: 125
      text: "{: 0.4f}".format(root.value)
      font_size: app.formats.font_size
      on_press: app.beep()
      on_release: Factory.Keypad().show(root, 'value')
