<FontItem>:
  height: 60
  size_hint_y: None

  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_press: app.beep()
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.7
      text: root.name
      font_size: app.formats.font_size
    FormValueButton:
      size_hint_x: None
      width: 250
      font_name: root.font_path
      font_size: 22
      text: "+123.456"
      on_press: app.beep()
      on_release:
        app.font_picker.callback = root.set_font
        app.font_picker.font_path = root.font_path
        app.manager.goto("font_picker")
