<NumberItem>:
  value: 0
  height: 60
  size_hint_y: None
  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_press: app.beep()
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.7
      text: root.name
    FormValueButton:
      size_hint_x: None
      width: 250
      text: str(root.value)
      on_press: app.beep()
      on_release: Factory.Keypad(integer=root.integer).show(root, 'value')