<StringItem>:
  height: 60
  size_hint_y: None
  BoxLayout:
    orientation: "horizontal"
    FormHelpButton:
      disabled: not root.help_file
      on_release: Factory.HelpPopup.show_help(root.help_file)
    FormLabel:
      size_hint_x: 0.7
      text: root.name
      font_size: app.formats.font_size
    FormTextInput:
      size_hint_x: None
      width: 250
      multiline: False
      text: root.value
      font_size: app.formats.font_size
      valign: "center"
      halign: "center"
      disabled: root.disabled
      on_text_validate: root.set_value_from_text(self.text)