#: import THEME reflex.components.widgets.facelift_theme

<TitleItem>:
  height: 36
  size_hint_y: None
  BoxLayout:
    orientation: "vertical"
    Label:
      text: root.name
      text_size: root.size
      font_name: THEME.FONT_BOLD
      color: THEME.ACCENT_TEXT
      font_size: app.formats.font_size
      valign: root.valign
      halign: root.halign
    Widget:
      height: 2
      width: root.width
      size_hint: None, None
      canvas:
        Color:
          rgba: THEME.BORDER
        Rectangle:
          size: self.size
          pos: self.pos
