#: import ToolbarButton reflex.components.toolbars.toolbar_button
#: import TwoStateButton reflex.components.toolbars.two_state_button
#: import TabSelector reflex.components.widgets.tab_selector
#: import IconButton reflex.components.widgets.icon_button
#: import Factory kivy.factory.Factory
#: import Keypad reflex.components.popups.keypad
#: import ModePopup reflex.components.popups.mode_popup

<HomeToolbar>:
  orientation: "vertical"
  width: self.height / 6
  size_hint_x: None
  size_hint_y: 1

  TabSelector:
    width: root.width
    size_hint_y: 1
    orientation: "vertical"
    selected: app.formats.current_format
    on_select: app.formats.toggle() if args[1] != app.formats.current_format else None
    TabSegment:
      text: "MM"
      value: "MM"
      font_size: min(self.height / 2.5, self.width / 2.5)
    TabSegment:
      text: "IN"
      value: "IN"
      font_size: min(self.height / 2.5, self.width / 2.5)

  ToolbarButton:
    width: root.width
    text: "P{:d}".format(app.currentOffset)
    on_release: Factory.Keypad(integer=True).show(app, 'currentOffset')
    size_hint_y: 1
    font_size: min(self.height/3, self.width/3)

  TabSelector:
    width: root.width
    size_hint_y: 1
    orientation: "vertical"
    selected: "ABS" if app.abs_mode else "INC"
    on_select: app.setter('abs_mode')(app, args[1] == "ABS")
    TabSegment:
      text: "ABS"
      value: "ABS"
      font_size: min(self.height / 2.5, self.width / 2.5)
    TabSegment:
      text: "INC"
      value: "INC"
      font_size: min(self.height / 2.5, self.width / 2.5)

  IconButton:
    width: root.width
    icon: "\ue2ca"
    on_release: app.manager.goto("plot")

    # Hide wizard button if show_wizard is False
    size_hint_y: 1 if app.formats.show_wizard else None
    height: self.height if app.formats.show_wizard else 0
    opacity: 1 if app.formats.show_wizard else 0
    disabled: not app.formats.show_wizard

  ToolbarButton:
    width: root.width
    text: root.current_mode_desc
    on_release:
      Factory.ModePopup().show_with_callback(app.set_mode, app.current_mode)
    size_hint_y: 1
    font_size: min(self.height/3, self.width/3)

  IconButton:
    width: root.width
    icon: "\uf085"
    on_release: app.manager.goto("setup_screen")
    size_hint_y: 1

  #Widget:
  #  size_hint_y: 1